#!/bin/bash

if [[ $(id -u) != 0 ]]; then
	clear
    whiptail --title "错误信息" --msgbox "请在root用户下执行" 8 78 
	exit 1
fi

if [[ $(uname -m 2> /dev/null) != x86_64 ]]; then
	clear
    whiptail --title "错误信息" --msgbox "请在64位系统下运行此脚本" 8 78 
	exit 1
fi

#操作系统判断
osdist(){

    set -e
    if cat /etc/*release | grep ^NAME | grep -q Debian; then

        dist=debian
        apt-get update -q
        export DEBIAN_FRONTEND=noninteractive
        apt-get install whiptail curl locales lsb-release jq dnsutils lsof -y -qq

    else
        clear
        whiptail --title "错误信息" --msgbox "本脚本只能在debian10下运行" 8 78     
        exit 1; 
    fi
}

dt_system_dep(){

rm -rf /etc/apt/sources.list.d/*
cat << EOF > /etc/apt/sources.list
deb http://mirrors.aliyun.com/debian $(cat /etc/os-release | grep VERSION= | cut -d '(' -f2 | cut -d ')' -f1) main
deb http://mirrors.aliyun.com/debian-security $(cat /etc/os-release | grep VERSION= | cut -d '(' -f2 | cut -d ')' -f1)/updates main
deb http://mirrors.aliyun.com/debian $(cat /etc/os-release | grep VERSION= | cut -d '(' -f2 | cut -d ')' -f1)-updates main
EOF

groupadd clash
useradd -g clash -d /home/clash -s /bin/bash -m clash

echo clash | sudo passwd clash --stdin  &>/dev/null

apt update

echo iptables-persistent iptables-persistent/autosave_v4 boolean true | debconf-set-selections
echo iptables-persistent iptables-persistent/autosave_v6 boolean true | debconf-set-selections

yes|apt -y install sudo supervisor iptables-persistent net-tools curl gzip unzip

source /etc/profile

echo "clash  ALL=(ALL:ALL) ALL" >> /etc/sudoers

cat << EOF > /etc/sysctl.conf

net.ipv4.ip_forward=1
fs.file-max = 999999

net.core.rmem_max = 67108864
net.core.wmem_max = 67108864
net.core.rmem_default = 6291456
net.core.wmem_default = 6291456
net.core.netdev_max_backlog = 65535
net.core.somaxconn = 262114

net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_fin_timeout = 30
net.ipv4.tcp_keepalive_time = 1200
net.ipv4.tcp_max_syn_backlog = 8192
net.ipv4.tcp_max_tw_buckets = 5000
net.ipv4.tcp_mem = 8192 131072 67108864
net.ipv4.tcp_rmem = 10240 87380 12582912
net.ipv4.tcp_wmem = 10240 87380 12582912
net.ipv4.tcp_mtu_probing = 1
net.ipv4.tcp_notsent_lowat = 16384
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_max_orphans= 262114
net.ipv4.tcp_fastopen = 3

net.ipv4.ip_local_port_range = 1024 65000

net.ipv4.udp_mem = 8192 131072 67108864
net.ipv4.udp_rmem_min = 4096
net.ipv4.udp_wmem_min = 4096
net.core.default_qdisc = fq
net.ipv4.tcp_congestion_control = bbr
EOF

sysctl -p
}

#trojan
dt_input_trojan(){
while [[ -z ${loc_ip} ]]; do
    loc_ip=$(whiptail --inputbox --nocancel "输入本机IP（现在安装灯塔客户端机器的ip）" 8 78 --title "输入域名" 3>&1 1>&2 2>&3)
done

while [[ -z ${gate_ip} ]]; do
    gate_ip=$(whiptail --inputbox --nocancel "输入网关IP（输入网关IP（ros的ip或者爱快ip）" 8 78 --title "输入域名" 3>&1 1>&2 2>&3)
done

# gate_ip=$(route -n | grep $ETH_N | grep UG | awk '{print $2}')

}


dt_smartdns(){

wget --no-check-certificate -O /opt/smartdns.deb $SM

cd /opt
dpkg -i smartdns.deb

cat << EOF > /etc/smartdns/smartdns.conf
bind :55
bind :56 -no-speed-check -group GFW -no-rule-addr
speed-check-mode tcp:443,tcp:80,ping
cache-size 0
rr-ttl 600
rr-ttl-min 60
rr-ttl-max 600
prefetch-domain yes
force-AAAA-SOA yes
serve-expired yes
serve-expired-ttl 0
log-level error
log-file /var/log/smartdns.log
log-size 2048k
log-num 2
conf-file /etc/smartdns/gfw_domain.conf

server 119.28.28.28
server 223.5.5.5
server 223.6.6.6 
server-tls dns.rubyfish.cn:853
server-tcp 8.8.8.8 -group GFW -exclude-default-group
server-tcp 8.8.4.4 -group GFW -exclude-default-group
server-tls dns.rubyfish.cn:853 -group GFW -exclude-default-group 
EOF

rm -rf /opt/smartdns.deb

cd /etc/smartdns/

wget --no-check-certificate $GFW_LIST

cd 

systemctl enable smartdns
systemctl start smartdns > /dev/null 2>&1

}

#trojan
dt_clash_trojan(){

wget --no-check-certificate -O /opt/clash.gz $CLS
cd /opt

gzip -d clash.gz
mv clash /usr/local/bin/clash
chmod +x /usr/local/bin/clash
# 为 clash 添加绑定低位端口的权限，这样运行 clash 的时候无需 root 权限
setcap cap_net_bind_service=+ep /usr/local/bin/clash

mkdir -p /home/clash/.config/clash

cat << EOF > /home/clash/.config/clash/config.yaml
port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: true
mode: Rule
log-level: info
external-controller: 0.0.0.0:9090
dns:
  enable: true
  listen: 0.0.0.0:53
  enhanced-mode: redir-host
  nameserver:
    - 127.0.0.1:55
  fallback:
    - 127.0.0.1:56
secret: miyue
external-ui: dashboard
Proxy:

Proxy Group:
  - name: ♻️ 自动选择
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - 🎯 全球直连
  - name: 🎯 全球直连
    type: select
    proxies:
      - DIRECT
  - name: 🐟 漏网之鱼
    type: select
    proxies:
      - 🎯 全球直连
      - ♻️ 自动选择
Rule:
 - DOMAIN-SUFFIX,local,🎯 全球直连
 - IP-CIDR,192.168.0.0/16,🎯 全球直连,no-resolve
 - IP-CIDR,10.0.0.0/8,🎯 全球直连,no-resolve
 - IP-CIDR,172.16.0.0/12,🎯 全球直连,no-resolve
 - IP-CIDR,127.0.0.0/8,🎯 全球直连,no-resolve
 - IP-CIDR,100.64.0.0/10,🎯 全球直连,no-resolve
 - IP-CIDR6,::1/128,🎯 全球直连,no-resolve
 - IP-CIDR6,fc00::/7,🎯 全球直连,no-resolve
 - IP-CIDR6,fe80::/10,🎯 全球直连,no-resolve
 - IP-CIDR6,fd00::/8,🎯 全球直连,no-resolve
 - DOMAIN,app.adjust.com,🎯 全球直连
 - DOMAIN-SUFFIX,googletraveladservices.com,🎯 全球直连
 - DOMAIN,dl.google.com,🎯 全球直连
 - DOMAIN,mtalk.google.com,🎯 全球直连
 - DOMAIN,livew.l.qq.com,🎯 全球直连
 - DOMAIN,vd.l.qq.com,🎯 全球直连
 - DOMAIN,analytics.strava.com,🎯 全球直连
 - DOMAIN,msg.umeng.com,🎯 全球直连
 - DOMAIN,msg.umengcloud.com,🎯 全球直连
 - DOMAIN-SUFFIX,qhres.com,🎯 全球直连
 - DOMAIN-SUFFIX,qhimg.com,🎯 全球直连
 - DOMAIN-SUFFIX,akadns.net,🎯 全球直连
 - DOMAIN-SUFFIX,alibaba.com,🎯 全球直连
 - DOMAIN-SUFFIX,alicdn.com,🎯 全球直连
 - DOMAIN-SUFFIX,alikunlun.com,🎯 全球直连
 - DOMAIN-SUFFIX,alipay.com,🎯 全球直连
 - DOMAIN-SUFFIX,amap.com,🎯 全球直连
 - DOMAIN-SUFFIX,autonavi.com,🎯 全球直连
 - DOMAIN-SUFFIX,dingtalk.com,🎯 全球直连
 - DOMAIN-SUFFIX,mxhichina.com,🎯 全球直连
 - DOMAIN-SUFFIX,soku.com,🎯 全球直连
 - DOMAIN-SUFFIX,taobao.com,🎯 全球直连
 - DOMAIN-SUFFIX,tmall.com,🎯 全球直连
 - DOMAIN-SUFFIX,tmall.hk,🎯 全球直连
 - DOMAIN-SUFFIX,ykimg.com,🎯 全球直连
 - DOMAIN-SUFFIX,youku.com,🎯 全球直连
 - DOMAIN-SUFFIX,xiami.com,🎯 全球直连
 - DOMAIN-SUFFIX,xiami.net,🎯 全球直连
 - DOMAIN-SUFFIX,aaplimg.com,🎯 全球直连
 - DOMAIN-SUFFIX,apple.co,🎯 全球直连
 - DOMAIN-SUFFIX,apple.com,🎯 全球直连
 - DOMAIN-SUFFIX,apple-cloudkit.com,🎯 全球直连
 - DOMAIN-SUFFIX,appstore.com,🎯 全球直连
 - DOMAIN-SUFFIX,cdn-apple.com,🎯 全球直连
 - DOMAIN-SUFFIX,crashlytics.com,🎯 全球直连
 - DOMAIN-SUFFIX,icloud.com,🎯 全球直连
 - DOMAIN-SUFFIX,icloud-content.com,🎯 全球直连
 - DOMAIN-SUFFIX,me.com,🎯 全球直连
 - DOMAIN-SUFFIX,mzstatic.com,🎯 全球直连
 - DOMAIN,www-cdn.icloud.com.akadns.net,🎯 全球直连
 - DOMAIN-SUFFIX,baidu.com,🎯 全球直连
 - DOMAIN-SUFFIX,baidubcr.com,🎯 全球直连
 - DOMAIN-SUFFIX,bdstatic.com,🎯 全球直连
 - DOMAIN-SUFFIX,yunjiasu-cdn.net,🎯 全球直连
 - DOMAIN-SUFFIX,acgvideo.com,🎯 全球直连
 - DOMAIN-SUFFIX,biliapi.com,🎯 全球直连
 - DOMAIN-SUFFIX,biliapi.net,🎯 全球直连
 - DOMAIN-SUFFIX,bilibili.com,🎯 全球直连
 - DOMAIN-SUFFIX,bilibili.tv,🎯 全球直连
 - DOMAIN-SUFFIX,hdslb.com,🎯 全球直连
 - DOMAIN-SUFFIX,blizzard.com,🎯 全球直连
 - DOMAIN-SUFFIX,battle.net,🎯 全球直连
 - DOMAIN,blzddist1-a.akamaihd.net,🎯 全球直连
 - DOMAIN-SUFFIX,feiliao.com,🎯 全球直连
 - DOMAIN-SUFFIX,pstatp.com,🎯 全球直连
 - DOMAIN-SUFFIX,snssdk.com,🎯 全球直连
 - DOMAIN-SUFFIX,iesdouyin.com,🎯 全球直连
 - DOMAIN-SUFFIX,toutiao.com,🎯 全球直连
 - DOMAIN-SUFFIX,cctv.com,🎯 全球直连
 - DOMAIN-SUFFIX,cctvpic.com,🎯 全球直连
 - DOMAIN-SUFFIX,livechina.com,🎯 全球直连
 - DOMAIN-SUFFIX,didialift.com,🎯 全球直连
 - DOMAIN-SUFFIX,didiglobal.com,🎯 全球直连
 - DOMAIN-SUFFIX,udache.com,🎯 全球直连
 - DOMAIN-SUFFIX,343480.com,🎯 全球直连
 - DOMAIN-SUFFIX,baduziyuan.com,🎯 全球直连
 - DOMAIN-SUFFIX,com-hs-hkdy.com,🎯 全球直连
 - DOMAIN-SUFFIX,czybjz.com,🎯 全球直连
 - DOMAIN-SUFFIX,dandanzan.com,🎯 全球直连
 - DOMAIN-SUFFIX,fjhps.com,🎯 全球直连
 - DOMAIN-SUFFIX,kuyunbo.club,🎯 全球直连
 - DOMAIN-SUFFIX,21cn.com,🎯 全球直连
 - DOMAIN-SUFFIX,hitv.com,🎯 全球直连
 - DOMAIN-SUFFIX,mgtv.com,🎯 全球直连
 - DOMAIN-SUFFIX,iqiyi.com,🎯 全球直连
 - DOMAIN-SUFFIX,iqiyipic.com,🎯 全球直连
 - DOMAIN-SUFFIX,71.am.com,🎯 全球直连
 - DOMAIN-SUFFIX,jd.com,🎯 全球直连
 - DOMAIN-SUFFIX,jd.hk,🎯 全球直连
 - DOMAIN-SUFFIX,jdpay.com,🎯 全球直连
 - DOMAIN-SUFFIX,360buyimg.com,🎯 全球直连
 - DOMAIN-SUFFIX,iciba.com,🎯 全球直连
 - DOMAIN-SUFFIX,ksosoft.com,🎯 全球直连
 - DOMAIN-SUFFIX,meitu.com,🎯 全球直连
 - DOMAIN-SUFFIX,meitudata.com,🎯 全球直连
 - DOMAIN-SUFFIX,meitustat.com,🎯 全球直连
 - DOMAIN-SUFFIX,meipai.com,🎯 全球直连
 - DOMAIN-SUFFIX,duokan.com,🎯 全球直连
 - DOMAIN-SUFFIX,mi-img.com,🎯 全球直连
 - DOMAIN-SUFFIX,miui.com,🎯 全球直连
 - DOMAIN-SUFFIX,miwifi.com,🎯 全球直连
 - DOMAIN-SUFFIX,xiaomi.com,🎯 全球直连
 - DOMAIN-SUFFIX,microsoft.com,🎯 全球直连
 - DOMAIN-SUFFIX,msecnd.net,🎯 全球直连
 - DOMAIN-SUFFIX,office365.com,🎯 全球直连
 - DOMAIN-SUFFIX,outlook.com,🎯 全球直连
 - DOMAIN-SUFFIX,s-microsoft.com,🎯 全球直连
 - DOMAIN-SUFFIX,visualstudio.com,🎯 全球直连
 - DOMAIN-SUFFIX,windows.com,🎯 全球直连
 - DOMAIN-SUFFIX,windowsupdate.com,🎯 全球直连
 - DOMAIN,officecdn-microsoft-com.akamaized.net,🎯 全球直连
 - DOMAIN-SUFFIX,163.com,🎯 全球直连
 - DOMAIN-SUFFIX,126.net,🎯 全球直连
 - DOMAIN-SUFFIX,127.net,🎯 全球直连
 - DOMAIN-SUFFIX,163yun.com,🎯 全球直连
 - DOMAIN-SUFFIX,lofter.com,🎯 全球直连
 - DOMAIN-SUFFIX,netease.com,🎯 全球直连
 - DOMAIN-SUFFIX,ydstatic.com,🎯 全球直连
 - DOMAIN-SUFFIX,sina.com,🎯 全球直连
 - DOMAIN-SUFFIX,weibo.com,🎯 全球直连
 - DOMAIN-SUFFIX,weibocdn.com,🎯 全球直连
 - DOMAIN-SUFFIX,sohu.com,🎯 全球直连
 - DOMAIN-SUFFIX,sohucs.com,🎯 全球直连
 - DOMAIN-SUFFIX,sohu-inc.com,🎯 全球直连
 - DOMAIN-SUFFIX,v-56.com,🎯 全球直连
 - DOMAIN-SUFFIX,sogo.com,🎯 全球直连
 - DOMAIN-SUFFIX,sogou.com,🎯 全球直连
 - DOMAIN-SUFFIX,sogoucdn.com,🎯 全球直连
 - DOMAIN-SUFFIX,steampowered.com,🎯 全球直连
 - DOMAIN-SUFFIX,steam-chat.com,🎯 全球直连
 - DOMAIN-SUFFIX,steamgames.com,🎯 全球直连
 - DOMAIN-SUFFIX,steamusercontent.com,🎯 全球直连
 - DOMAIN-SUFFIX,steamcontent.com,🎯 全球直连
 - DOMAIN-SUFFIX,steamstatic.com,🎯 全球直连
 - DOMAIN-SUFFIX,steamcdn-a.akamaihd.net,🎯 全球直连
 - DOMAIN-SUFFIX,steamstat.us,🎯 全球直连
 - DOMAIN-SUFFIX,gtimg.com,🎯 全球直连
 - DOMAIN-SUFFIX,idqqimg.com,🎯 全球直连
 - DOMAIN-SUFFIX,igamecj.com,🎯 全球直连
 - DOMAIN-SUFFIX,myapp.com,🎯 全球直连
 - DOMAIN-SUFFIX,myqcloud.com,🎯 全球直连
 - DOMAIN-SUFFIX,qq.com,🎯 全球直连
 - DOMAIN-SUFFIX,servicewechat.com,🎯 全球直连
 - DOMAIN-SUFFIX,tencent.com,🎯 全球直连
 - DOMAIN-SUFFIX,tencent-cloud.net,🎯 全球直连
 - DOMAIN-SUFFIX,tenpay.com,🎯 全球直连
 - DOMAIN,file-igamecj.akamaized.net,🎯 全球直连
 - DOMAIN-SUFFIX,jstucdn.com,🎯 全球直连
 - DOMAIN-SUFFIX,zimuzu.io,🎯 全球直连
 - DOMAIN-SUFFIX,zimuzu.tv,🎯 全球直连
 - DOMAIN-SUFFIX,zmz2019.com,🎯 全球直连
 - DOMAIN-SUFFIX,zmzapi.com,🎯 全球直连
 - DOMAIN-SUFFIX,zmzapi.net,🎯 全球直连
 - DOMAIN-SUFFIX,zmzfile.com,🎯 全球直连
 - DOMAIN-SUFFIX,ccgslb.com,🎯 全球直连
 - DOMAIN-SUFFIX,ccgslb.net,🎯 全球直连
 - DOMAIN-SUFFIX,chinanetcenter.com,🎯 全球直连
 - DOMAIN-SUFFIX,meixincdn.com,🎯 全球直连
 - DOMAIN-SUFFIX,ourdvs.com,🎯 全球直连
 - DOMAIN-SUFFIX,staticdn.net,🎯 全球直连
 - DOMAIN-SUFFIX,wangsu.com,🎯 全球直连
 - DOMAIN-SUFFIX,ipip.net,🎯 全球直连
 - DOMAIN-SUFFIX,ip.la,🎯 全球直连
 - DOMAIN-SUFFIX,ip-cdn.com,🎯 全球直连
 - DOMAIN-SUFFIX,ipv6-test.com,🎯 全球直连
 - DOMAIN-SUFFIX,test-ipv6.com,🎯 全球直连
 - DOMAIN-SUFFIX,whatismyip.com,🎯 全球直连
 - DOMAIN-SUFFIX,netspeedtestmaster.com,🎯 全球直连
 - DOMAIN,speedtest.macpaw.com,🎯 全球直连
 - DOMAIN-SUFFIX,awesome-hd.me,🎯 全球直连
 - DOMAIN-SUFFIX,broadcasthe.net,🎯 全球直连
 - DOMAIN-SUFFIX,chdbits.co,🎯 全球直连
 - DOMAIN-SUFFIX,classix-unlimited.co.uk,🎯 全球直连
 - DOMAIN-SUFFIX,empornium.me,🎯 全球直连
 - DOMAIN-SUFFIX,gazellegames.net,🎯 全球直连
 - DOMAIN-SUFFIX,hdchina.org,🎯 全球直连
 - DOMAIN-SUFFIX,hdsky.me,🎯 全球直连
 - DOMAIN-SUFFIX,icetorrent.org,🎯 全球直连
 - DOMAIN-SUFFIX,jpopsuki.eu,🎯 全球直连
 - DOMAIN-SUFFIX,keepfrds.com,🎯 全球直连
 - DOMAIN-SUFFIX,madsrevolution.net,🎯 全球直连
 - DOMAIN-SUFFIX,m-team.cc,🎯 全球直连
 - DOMAIN-SUFFIX,nanyangpt.com,🎯 全球直连
 - DOMAIN-SUFFIX,ncore.cc,🎯 全球直连
 - DOMAIN-SUFFIX,open.cd,🎯 全球直连
 - DOMAIN-SUFFIX,ourbits.club,🎯 全球直连
 - DOMAIN-SUFFIX,passthepopcorn.me,🎯 全球直连
 - DOMAIN-SUFFIX,privatehd.to,🎯 全球直连
 - DOMAIN-SUFFIX,redacted.ch,🎯 全球直连
 - DOMAIN-SUFFIX,springsunday.net,🎯 全球直连
 - DOMAIN-SUFFIX,tjupt.org,🎯 全球直连
 - DOMAIN-SUFFIX,totheglory.im,🎯 全球直连
 - DOMAIN-SUFFIX,acm.org,🎯 全球直连
 - DOMAIN-SUFFIX,acs.org,🎯 全球直连
 - DOMAIN-SUFFIX,aip.org,🎯 全球直连
 - DOMAIN-SUFFIX,ams.org,🎯 全球直连
 - DOMAIN-SUFFIX,annualreviews.org,🎯 全球直连
 - DOMAIN-SUFFIX,aps.org,🎯 全球直连
 - DOMAIN-SUFFIX,ascelibrary.org,🎯 全球直连
 - DOMAIN-SUFFIX,asm.org,🎯 全球直连
 - DOMAIN-SUFFIX,asme.org,🎯 全球直连
 - DOMAIN-SUFFIX,astm.org,🎯 全球直连
 - DOMAIN-SUFFIX,bmj.com,🎯 全球直连
 - DOMAIN-SUFFIX,cambridge.org,🎯 全球直连
 - DOMAIN-SUFFIX,cas.org,🎯 全球直连
 - DOMAIN-SUFFIX,clarivate.com,🎯 全球直连
 - DOMAIN-SUFFIX,ebscohost.com,🎯 全球直连
 - DOMAIN-SUFFIX,emerald.com,🎯 全球直连
 - DOMAIN-SUFFIX,engineeringvillage.com,🎯 全球直连
 - DOMAIN-SUFFIX,icevirtuallibrary.com,🎯 全球直连
 - DOMAIN-SUFFIX,ieee.org,🎯 全球直连
 - DOMAIN-SUFFIX,imf.org,🎯 全球直连
 - DOMAIN-SUFFIX,iop.org,🎯 全球直连
 - DOMAIN-SUFFIX,jamanetwork.com,🎯 全球直连
 - DOMAIN-SUFFIX,jhu.edu,🎯 全球直连
 - DOMAIN-SUFFIX,jstor.org,🎯 全球直连
 - DOMAIN-SUFFIX,karger.com,🎯 全球直连
 - DOMAIN-SUFFIX,libguides.com,🎯 全球直连
 - DOMAIN-SUFFIX,madsrevolution.net,🎯 全球直连
 - DOMAIN-SUFFIX,mpg.de,🎯 全球直连
 - DOMAIN-SUFFIX,myilibrary.com,🎯 全球直连
 - DOMAIN-SUFFIX,nature.com,🎯 全球直连
 - DOMAIN-SUFFIX,oecd-ilibrary.org,🎯 全球直连
 - DOMAIN-SUFFIX,osapublishing.org,🎯 全球直连
 - DOMAIN-SUFFIX,oup.com,🎯 全球直连
 - DOMAIN-SUFFIX,ovid.com,🎯 全球直连
 - DOMAIN-SUFFIX,oxfordartonline.com,🎯 全球直连
 - DOMAIN-SUFFIX,oxfordbibliographies.com,🎯 全球直连
 - DOMAIN-SUFFIX,oxfordmusiconline.com,🎯 全球直连
 - DOMAIN-SUFFIX,pnas.org,🎯 全球直连
 - DOMAIN-SUFFIX,proquest.com,🎯 全球直连
 - DOMAIN-SUFFIX,rsc.org,🎯 全球直连
 - DOMAIN-SUFFIX,sagepub.com,🎯 全球直连
 - DOMAIN-SUFFIX,sciencedirect.com,🎯 全球直连
 - DOMAIN-SUFFIX,sciencemag.org,🎯 全球直连
 - DOMAIN-SUFFIX,scopus.com,🎯 全球直连
 - DOMAIN-SUFFIX,siam.org,🎯 全球直连
 - DOMAIN-SUFFIX,spiedigitallibrary.org,🎯 全球直连
 - DOMAIN-SUFFIX,springer.com,🎯 全球直连
 - DOMAIN-SUFFIX,springerlink.com,🎯 全球直连
 - DOMAIN-SUFFIX,tandfonline.com,🎯 全球直连
 - DOMAIN-SUFFIX,un.org,🎯 全球直连
 - DOMAIN-SUFFIX,uni-bielefeld.de,🎯 全球直连
 - DOMAIN-SUFFIX,webofknowledge.com,🎯 全球直连
 - DOMAIN-SUFFIX,westlaw.com,🎯 全球直连
 - DOMAIN-SUFFIX,wiley.com,🎯 全球直连
 - DOMAIN-SUFFIX,worldbank.org,🎯 全球直连
 - DOMAIN-SUFFIX,worldscientific.com,🎯 全球直连
 - DOMAIN-SUFFIX,cn,🎯 全球直连
 - DOMAIN-SUFFIX,360in.com,🎯 全球直连
 - DOMAIN-SUFFIX,51ym.me,🎯 全球直连
 - DOMAIN-SUFFIX,8686c.com,🎯 全球直连
 - DOMAIN-SUFFIX,abchina.com,🎯 全球直连
 - DOMAIN-SUFFIX,accuweather.com,🎯 全球直连
 - DOMAIN-SUFFIX,aicoinstorge.com,🎯 全球直连
 - DOMAIN-SUFFIX,air-matters.com,🎯 全球直连
 - DOMAIN-SUFFIX,air-matters.io,🎯 全球直连
 - DOMAIN-SUFFIX,aixifan.com,🎯 全球直连
 - DOMAIN-SUFFIX,amd.com,🎯 全球直连
 - DOMAIN-SUFFIX,b612.net,🎯 全球直连
 - DOMAIN-SUFFIX,bdatu.com,🎯 全球直连
 - DOMAIN-SUFFIX,beitaichufang.com,🎯 全球直连
 - DOMAIN-SUFFIX,bjango.com,🎯 全球直连
 - DOMAIN-SUFFIX,booking.com,🎯 全球直连
 - DOMAIN-SUFFIX,bstatic.com,🎯 全球直连
 - DOMAIN-SUFFIX,cailianpress.com,🎯 全球直连
 - DOMAIN-SUFFIX,camera360.com,🎯 全球直连
 - DOMAIN-SUFFIX,chinaso.com,🎯 全球直连
 - DOMAIN-SUFFIX,chua.pro,🎯 全球直连
 - DOMAIN-SUFFIX,chuimg.com,🎯 全球直连
 - DOMAIN-SUFFIX,chunyu.mobi,🎯 全球直连
 - DOMAIN-SUFFIX,chushou.tv,🎯 全球直连
 - DOMAIN-SUFFIX,cmbchina.com,🎯 全球直连
 - DOMAIN-SUFFIX,cmbimg.com,🎯 全球直连
 - DOMAIN-SUFFIX,ctrip.com,🎯 全球直连
 - DOMAIN-SUFFIX,dfcfw.com,🎯 全球直连
 - DOMAIN-SUFFIX,docschina.org,🎯 全球直连
 - DOMAIN-SUFFIX,douban.com,🎯 全球直连
 - DOMAIN-SUFFIX,doubanio.com,🎯 全球直连
 - DOMAIN-SUFFIX,douyu.com,🎯 全球直连
 - DOMAIN-SUFFIX,dxycdn.com,🎯 全球直连
 - DOMAIN-SUFFIX,dytt8.net,🎯 全球直连
 - DOMAIN-SUFFIX,eastmoney.com,🎯 全球直连
 - DOMAIN-SUFFIX,eudic.net,🎯 全球直连
 - DOMAIN-SUFFIX,feng.com,🎯 全球直连
 - DOMAIN-SUFFIX,fengkongcloud.com,🎯 全球直连
 - DOMAIN-SUFFIX,frdic.com,🎯 全球直连
 - DOMAIN-SUFFIX,futu5.com,🎯 全球直连
 - DOMAIN-SUFFIX,futunn.com,🎯 全球直连
 - DOMAIN-SUFFIX,gandi.net,🎯 全球直连
 - DOMAIN-SUFFIX,geilicdn.com,🎯 全球直连
 - DOMAIN-SUFFIX,getpricetag.com,🎯 全球直连
 - DOMAIN-SUFFIX,gifshow.com,🎯 全球直连
 - DOMAIN-SUFFIX,godic.net,🎯 全球直连
 - DOMAIN-SUFFIX,hicloud.com,🎯 全球直连
 - DOMAIN-SUFFIX,hongxiu.com,🎯 全球直连
 - DOMAIN-SUFFIX,hostbuf.com,🎯 全球直连
 - DOMAIN-SUFFIX,huxiucdn.com,🎯 全球直连
 - DOMAIN-SUFFIX,huya.com,🎯 全球直连
 - DOMAIN-SUFFIX,infinitynewtab.com,🎯 全球直连
 - DOMAIN-SUFFIX,ithome.com,🎯 全球直连
 - DOMAIN-SUFFIX,java.com,🎯 全球直连
 - DOMAIN-SUFFIX,jidian.im,🎯 全球直连
 - DOMAIN-SUFFIX,kaiyanapp.com,🎯 全球直连
 - DOMAIN-SUFFIX,kaspersky-labs.com,🎯 全球直连
 - DOMAIN-SUFFIX,keepcdn.com,🎯 全球直连
 - DOMAIN-SUFFIX,kkmh.com,🎯 全球直连
 - DOMAIN-SUFFIX,licdn.com,🎯 全球直连
 - DOMAIN-SUFFIX,linkedin.com,🎯 全球直连
 - DOMAIN-SUFFIX,loli.net,🎯 全球直连
 - DOMAIN-SUFFIX,luojilab.com,🎯 全球直连
 - DOMAIN-SUFFIX,maoyan.com,🎯 全球直连
 - DOMAIN-SUFFIX,maoyun.tv,🎯 全球直连
 - DOMAIN-SUFFIX,meituan.com,🎯 全球直连
 - DOMAIN-SUFFIX,meituan.net,🎯 全球直连
 - DOMAIN-SUFFIX,mobike.com,🎯 全球直连
 - DOMAIN-SUFFIX,moke.com,🎯 全球直连
 - DOMAIN-SUFFIX,mubu.com,🎯 全球直连
 - DOMAIN-SUFFIX,myzaker.com,🎯 全球直连
 - DOMAIN-SUFFIX,nim-lang-cn.org,🎯 全球直连
 - DOMAIN-SUFFIX,nvidia.com,🎯 全球直连
 - DOMAIN-SUFFIX,oracle.com,🎯 全球直连
 - DOMAIN-SUFFIX,paypal.com,🎯 全球直连
 - DOMAIN-SUFFIX,paypalobjects.com,🎯 全球直连
 - DOMAIN-SUFFIX,qdaily.com,🎯 全球直连
 - DOMAIN-SUFFIX,qidian.com,🎯 全球直连
 - DOMAIN-SUFFIX,qyer.com,🎯 全球直连
 - DOMAIN-SUFFIX,qyerstatic.com,🎯 全球直连
 - DOMAIN-SUFFIX,raychase.net,🎯 全球直连
 - DOMAIN-SUFFIX,ronghub.com,🎯 全球直连
 - DOMAIN-SUFFIX,ruguoapp.com,🎯 全球直连
 - DOMAIN-SUFFIX,s-reader.com,🎯 全球直连
 - DOMAIN-SUFFIX,sankuai.com,🎯 全球直连
 - DOMAIN-SUFFIX,scomper.me,🎯 全球直连
 - DOMAIN-SUFFIX,seafile.com,🎯 全球直连
 - DOMAIN-SUFFIX,sm.ms,🎯 全球直连
 - DOMAIN-SUFFIX,smzdm.com,🎯 全球直连
 - DOMAIN-SUFFIX,snapdrop.net,🎯 全球直连
 - DOMAIN-SUFFIX,snwx.com,🎯 全球直连
 - DOMAIN-SUFFIX,sspai.com,🎯 全球直连
 - DOMAIN-SUFFIX,takungpao.com,🎯 全球直连
 - DOMAIN-SUFFIX,teamviewer.com,🎯 全球直连
 - DOMAIN-SUFFIX,tianyancha.com,🎯 全球直连
 - DOMAIN-SUFFIX,udacity.com,🎯 全球直连
 - DOMAIN-SUFFIX,uning.com,🎯 全球直连
 - DOMAIN-SUFFIX,vmware.com,🎯 全球直连
 - DOMAIN-SUFFIX,weather.com,🎯 全球直连
 - DOMAIN-SUFFIX,weico.cc,🎯 全球直连
 - DOMAIN-SUFFIX,weidian.com,🎯 全球直连
 - DOMAIN-SUFFIX,xiachufang.com,🎯 全球直连
 - DOMAIN-SUFFIX,ximalaya.com,🎯 全球直连
 - DOMAIN-SUFFIX,xinhuanet.com,🎯 全球直连
 - DOMAIN-SUFFIX,xmcdn.com,🎯 全球直连
 - DOMAIN-SUFFIX,yangkeduo.com,🎯 全球直连
 - DOMAIN-SUFFIX,zhangzishi.cc,🎯 全球直连
 - DOMAIN-SUFFIX,zhihu.com,🎯 全球直连
 - DOMAIN-SUFFIX,zhimg.com,🎯 全球直连
 - DOMAIN-SUFFIX,zhuihd.com,🎯 全球直连
 - DOMAIN,download.jetbrains.com,🎯 全球直连
 - DOMAIN,images-cn.ssl-images-amazon.com,🎯 全球直连
 - IP-CIDR,119.28.28.28/32,🎯 全球直连,no-resolve
 - DOMAIN-SUFFIX,smtp,🎯 全球直连
 - DOMAIN-KEYWORD,aria2,🎯 全球直连
 - GEOIP,CN,🎯 全球直连
 - MATCH,🐟 漏网之鱼
EOF

cd /home/clash/.config/clash

wget --no-check-certificate $MMDB

mkdir dashboard

wget --no-check-certificate $DASH

unzip clash-dashboard-gh-pages.zip

mv clash-dashboard-gh-pages/* dashboard/

chown -R clash /home/clash/.config/

chmod +x /home/clash/.config/clash/Country.mmdb

cat << EOF > /lib/systemd/system/clash@.service
[Unit]
Description=A rule based proxy in Go for %i.
After=network.target

[Service]
Type=simple
User=%i
Restart=on-abort
ExecStart=/usr/local/bin/clash

[Install]
WantedBy=multi-user.target
EOF


systemctl daemon-reload

systemctl enable clash@clash

systemctl start clash@clash > /dev/null 2>&1

sleep 5
}


dt_iptables(){

temp_ip=(${loc_ip//./ })

jy_ip=${temp_ip[0]}"."${temp_ip[1]}".0.0"

iptables -t nat -N clash
echo "1******************************************************************"
iptables -t nat -N clash_dns
echo "2******************************************************************"
iptables -t nat -A PREROUTING -p tcp --dport 53 -d $jy_ip/16 -j clash_dns
echo "3******************************************************************"
iptables -t nat -A PREROUTING -p udp --dport 53 -d $jy_ip/16 -j clash_dns
echo "4******************************************************************"
iptables -t nat -A PREROUTING -p tcp -j clash
echo "5******************************************************************"

iptables -t nat -A clash_dns -p udp --dport 53 -d $jy_ip/16 -j DNAT --to-destination $loc_ip:53
# iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53
# iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53
echo "6******************************************************************"
iptables -t nat -A clash_dns -p tcp --dport 53 -d $jy_ip/16 -j DNAT --to-destination $loc_ip:53
echo "7******************************************************************"
#注意：这里的网段和IP你需要自己适配自己的
iptables -t nat -A clash -d 0.0.0.0/8 -j RETURN
iptables -t nat -A clash -d 10.0.0.0/8 -j RETURN
iptables -t nat -A clash -d 127.0.0.0/8 -j RETURN
iptables -t nat -A clash -d 169.254.0.0/16 -j RETURN
iptables -t nat -A clash -d 172.16.0.0/12 -j RETURN
iptables -t nat -A clash -d 192.168.0.0/16 -j RETURN
iptables -t nat -A clash -d 224.0.0.0/4 -j RETURN
iptables -t nat -A clash -d 240.0.0.0/4 -j RETURN
echo "8******************************************************************"
# iptables -t nat -A clash -p tcp --dport 22 -d $loc_ip/24 -j ACCEPT
# -A PREROUTING -p tcp -m multiport --sports 443,3389,1194 -j RETURN
iptables -t nat -I PREROUTING -p tcp -m multiport --sports 443,1194,3128,3389,3690,5000,5001 -j RETURN
iptables -t nat -A clash -p tcp -j REDIRECT --to-ports 7892
echo "9******************************************************************"
iptables -t nat -A OUTPUT -p tcp -m owner ! --uid-owner clash -j REDIRECT --to-port 7892
echo "10******************************************************************"
netfilter-persistent save
echo "11******************************************************************"
netfilter-persistent start
echo "12******************************************************************"
iptables-save  > /etc/iptables/rules.v4
echo "13******************************************************************"
}


set_ip_dns(){

cat << EOF > /etc/network/interfaces
source /etc/network/interfaces.d/*

auto lo

auto  $ETH_N
iface $ETH_N inet static
  address $loc_ip
  netmask 255.255.255.0
  gateway $gate_ip
EOF

echo "14******************************************************************"
}

dt_menu() {
 Mainmenu=$(whiptail --clear --ok-button "确定" --backtitle "version:20200405v1" --title "灯塔客户端v4.2" --menu --nocancel "
**********************************************************************************
简介：灯塔客户端v4.2(最简单的安装 最简单的使用)
系统：Debian10
Youtube：米月、Unicom
电报群：https://t.me/mi_yue
Youtube频道地址：https://t.im/n21o
**********************************************************************************
请选择需要安装的内容：
    " 22 86 5\
        "1" " 安装灯塔客户端"\
        "2" " 退出" 3>&1 1>&2 2>&3)
    case $Mainmenu in
        1)
        dt_system_dep
        dt_input_trojan
        dt_smartdns
        dt_clash_trojan
        dt_iptables
        set_ip_dns
        whiptail --title "灯塔客户端安装成功" --msgbox "
*************************************************************************
灯塔客户端安装成功，把需要留学机器的网关和dns改成灯塔客户端ip。软路由请自行修改。

灯塔客户端IP：$loc_ip
Youtube：米月、Unicom
电报群：https://t.me/mi_yue
Youtube频道地址：https://t.im/n21o
灯塔web页面:http://$loc_ip:9090/ui/
DNS上游修改地址：/etc/smartdns/smartdns.conf
灯塔客户端配置文件地址：/home/clash/.config/clash/config.yaml
*************************************************************************" 18 78
        clear
        ;;
        2)
        #exit
        clear
        whiptail --title "脚本已退出" --msgbox "真希望把你留住" 8 78
        ;;
        esac
}

ETH_N=$(ip --oneline link show up | grep -v "lo" | awk '{print$2;exit}' | cut -d':' -f1 | cut -d'@' -f1)
GFW_LIST="https://storage.rinvay.co/Smartdns/gfw_domain.conf"
SM="https://storage.rinvay.co/Smartdns/smartdns.1.2020.02.25-2212.x86_64-debian-all.deb"
CLS="https://storage.rinvay.co/Clash/clashr-linux-amd64-v0.19.0.1.gz"
DASH="https://storage.rinvay.co/Clash/clash-dashboard-gh-pages.zip"
MMDB="https://storage.rinvay.co/Clash/Country.mmdb"

dt_menu
